setwd("/Users/hegemb/mesothelioma/")
data.s1<-read.table("quant_S1.sf.txt",header=TRUE)
data.s2<-read.table("quant_S2.sf.txt",header=TRUE)
data.s3<-read.table("quant_S3.sf.txt",header=TRUE)
data.s4<-read.table("quant_S4.sf.txt",header=TRUE)
countData<-cbind(data.s1$TPM,data.s2$TPM,data.s3$TPM,data.s4$TPM)
row.names(countData)<-data.s1[,1]
colnames(countData)<-c("s1","s2","s3","s4")
countData<-round(countData)
colData<-matrix(c("after",rep("before",3)),ncol=1)
colnames(colData)<-"condition"
rownames(colData)<-colnames(countData)
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData = countData,colData=colData,design=~condition)
dds <- DESeq(dds)
res <- results(dds)
ix<-which(res$padj<0.1)
o<-order(res$padj)
res2<-res[o,]
#top20
v<-match(rownames(res2)[1:20],rownames(res))
countData[v,]
source("http://bioconductor.org/biocLite.R")
#biocLite("biomaRt")
library(biomaRt)
ensembl = useEnsembl(biomart="ensembl", dataset="hsapiens_gene_ensembl")
mappings<-getBM(attributes=c('ensembl_transcript_id','ensembl_gene_id','external_gene_name'),mart=ensembl)
m<-match(substr(row.names(res2),1,15),mappings[,1])
res3<-cbind(mappings[m,],res2,countData[o,])
row.names(res3)<-row.names(res2)
write.table(res3,file="deseq-res.txt",sep="\t",row.names=TRUE,col.names=TRUE,quote=FALSE)
